### ISSUE TITLE
improve readme to explain a bit about plugins/namespaces

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/vent-plugins#10]
For reference: https://raw.githubusercontent.com/CyberReboot/vent/master/docs/images/workflow.png

**Comment by ShreyaSa** [comment]
I'll look into this, okay?

**Comment by cglewis** [comment]
@ShreyaSa thank you! 👍

**Comment by tsheaiqt** [comment]
Hi, I haven't seen any work on this so I'm going to contribute.
