### ISSUE TITLE
Plugin Logging

### ISSUE THREAD

**Issue by pbronez** [CyberReboot/vent-plugins#24]
Looks like the current plugins have pretty minimal logging -- just printing to std out. How does Vent handle this output? Would it be valuable to pull together more verbose logs?

**Comment by pbronez** [comment]
For example, there are currently a lot of opportunities for silent failures. The dshell netflow parser [silently drops records](https://github.com/CyberReboot/vent-plugins/blob/master/plugins/network/dshell_netflow_parser/dshell_netflow_parser.py#L89) when parsing fails or the RabbitMQ connection drops during tool execution.

This could be improved in a couple ways:

1. Catch known exceptions, send to stderr, then continue
2. Print error to stdout, similar to as done elsewhere in the tools
3. Same as 2, but use Python's logging module to add additional metadata to the error report.

**Comment by cglewis** [comment]
anything that is logged to stdout/stderr will automatically get logged into syslog on vent at runtime, those logs can then be searched/filtered through the logs menu under `system commands`, or through the shell using docker command to interact with the syslog server.  also the syslog messages are also sent to elasticsearch in its own syslog index for easy searching.

all that said, it is up to the author of the plugin to provide that logging for it to be exposed to vent.

**Comment by cglewis** [comment]
i'm open to ideas if you have something in mind for making that standard for all plugins

**Comment by cglewis** [comment]
closing, as there has been no new activity in over 3 years.
