### ISSUE TITLE
Plugin Testing

### ISSUE THREAD

**Issue by pbronez** [CyberReboot/vent-plugins#25]
There is currently no uniform way to test plugins before loading them into vent. It would be useful to have a standard way to point to input files and their expected output, then run tests against that. The solution needs to be language agnostic.

[Sharness](http://chriscool.github.io/sharness/) might be a good fit:

> Sharness is a portable shell library to write, run, and analyze automated tests for Unix programs. Since all tests output TAP, the Test Anything Protocol, they can be run with any TAP harness.

Here's an example of how Sharness is used by [IPFS-go](https://github.com/ipfs/go-ipfs/tree/master/test/sharness). Since it uses a standard output format ([TAP](https://testanything.org/)) it would be a good excuse to add some plugins and visualization tools for that standard.

**Comment by pbronez** [comment]
Once a testing library is chosen, we need to define a standard for how to deal with test files.

It seems to me that test files and tests themselves should be contained within the directory for each tool. The one challenge here is that we may need large files to stress the system, and you wouldn't want these stored in git. Those could be simply be hosted elsewhere and downloaded at runtime by the test script.

**Comment by pbronez** [comment]
Needs a `test` label 😄

**Comment by pbronez** [comment]
It looks like there's some log duplication happening. When I look at logs in Vent, messages sent to `stdout` appear stand alone and again with a lot of extra prefix information. If Vent can handle the essential metadata, maybe the plugins should keep things pretty simple.

Key information for each entry includes:

- Plugin name (+ version?)
- Input file name
- Timestamp
- Error level (INFO, WARNING)

**Comment by cglewis** [comment]
oh, versioning of plugins is a great idea, i like it, maybe use the commit ID from the git repo?

**Comment by pbronez** [comment]
I agree that a hash id would be more useful semvar since the plugins aren't maintained as independent projects. Based on [this](https://gist.github.com/masak/2415865), I think CommitID includes sufficient data to uniquely identify the code (the full tree, not just the diff).

However, it might make more sense to identify it based on the plug-ins docker image. That would make it easy to map from the logs to an executable version of that code.

**Comment by cglewis** [comment]
yeah, we could also make it the hash of the image, which would definitely be immutable for the layers of that image build

**Comment by pbronez** [comment]
I think the current approach to namespaces and plugin deployment is working against us in the testing side. It pops up in a couple places:

- You can't run a tool in isolation, even though it's got a dockerfile
- Nothing can be tested locally, you have to upload to Github (on master branch!) and load into vent from there
- Vent doesn't tell you what plugins (or versions) you have loaded -- just that you have "vent-plugins" loaded.

I think there are a couple ways this could be refactored to improve things:

First, replace the top-level `templates` with per-tool `input.yml` or similar. Use this information to route appropriate files to the tool.

Now that tools don't depend on a top-level template, you can break them out into their own repos. Make Vent support both "single-tool" repos and "folder-of-tools" repos. These "folder-of-tools" repos are your new namespaces, and can be used when you have a set of logically related tools you want to manage as a group.

I still thing Sharness is a reasonable standard for testing. Tests could be defined at either the namespace or tool level. If defined at the tool level, there needs to be some kind of switch to ignore the test files when building a docker image intended for production. Namespace level test data should be dropped automatically when loaded in production mode.

There will need to be a standard test harness that includes RabbitMQ (and perhaps other things) to simulate the Vent environment. I'm not sure what the best way is to define expect messages on RabbitMQ for testing.

**Comment by cglewis** [comment]
good ideas, will digest.

**Comment by cglewis** [comment]
@pbronez just a quick update, after a refactor session with @cprafullchandra we're going to start moving towards a lot of this in an experimental branch.

specifically: running tools in isolation, a `yml/json` file per tool, and versioning of everything for easy understanding of logging and other runtime issues.  

thanks for taking the time to think through and test this for us as we work towards improving vent.

**Comment by cglewis** [comment]
now that reasonable testing is in place, closing this out for now.
