### ISSUE TITLE
Update Contributing.md To Reflect Master Requirement

### ISSUE THREAD

**Issue by pbronez** [CyberReboot/vent-plugins#26]
Vent only loads plugins on the `Master` branch, but the [contributing guidelines](https://github.com/CyberReboot/vent-plugins/blob/master/CONTRIBUTING.md) tell you to work on a feature branch. With current vent settings, this prevents the plugin from being deployed, even for testing.

I'll update the guidelines to reflect this.

**Comment by cglewis** [comment]
nice catch

**Comment by pbronez** [comment]
Needs a "docs" label 😄
