### ISSUE TITLE
Create a Plugin That Translates CSV to RDF

### ISSUE THREAD

**Issue by pbronez** [CyberReboot/vent-plugins#29]
Vent can handle plugins dumping files back into the input. It could be helpful to translate arbitrary files into RDF, so they can be combined as linked data. A CSV-to-RDF converter would be a good first step in that direction, and could be accomplished by simply wrapping [Tarql](http://tarql.github.io/). I'll take a look at this.

**Comment by cglewis** [comment]
closing, as there has been no new activity in over 3 years.
