### ISSUE TITLE
tool name missing for tcpdump hex parser

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/vent-plugins#56]

**Comment by daringer** [comment]
mmmh, don't get it, seems like the tool name for the tcpdump hex parser is already there, see [here](https://github.com/CyberReboot/vent-plugins/blob/master/tcpdump_hex_parser/vent.template#L2)...

**Comment by cglewis** [comment]
@daringer see https://github.com/CyberReboot/vent-plugins/blob/master/dshell_netflow_parser/dshell_netflow_parser.py#L60 for what it should look like.

**Comment by daringer** [comment]
too late :smile: damn
