### ISSUE TITLE
create a new namespace that handles XML files

### ISSUE THREAD

**Issue by cglewis** [CyberReboot/vent-plugins#9]

**Comment by harry-7** [comment]
I want to work on this. Can you explain what exactly do you mean by namespaces?

**Comment by cglewis** [comment]
sure, so if you look in this repo, there is currently a `namespace` for `network` here: https://github.com/CyberReboot/vent-plugins/tree/master/plugins/network

Under that namespace there are two tools (apps) packaged up with Dockerfiles.  For this, basically, you'd create a new namespace at the same level as `network` and underneath create a new app that handles XML files.

Note in your Dockerfile of your app, you'll want to leave the `CMD` at the end to be like so:
https://github.com/CyberReboot/vent-plugins/blob/master/plugins/network/dshell_netflow_parser/Dockerfile#L32

With that setup, when this plugin is installed on [vent](https://github.com/cyberreboot/vent), it will automatically add a volume and and path to the file being processed as the `CMD`, so in your app you can expect the first argument passed into your `ENTRYPOINT` from `CMD` to be the path of the file and that it's something the app can read.

You can output the results of reading the XML however you find useful, however, most plugins to date for vent have been sending the output as messages to rabbitmq since the apps automatically get a connection to rabbitmq inside of vent - check out the other apps under the network namespace for how that works.

Finally, you'll want to add your own template for your new namespace, like the `network.template` under templates.  There you can specify things like the extensions that the namespace is intended to process (i.e. `.xml`) or even the mimetypes.

Let me know if you have further questions, happy to help get you kickstarted, and thanks for the help!

**Comment by harry-7** [comment]
@cglewis Thanks for info. I have a few more questions.
- How can I check this out so that I can get familiarity with vent and Vent plugins?
- what  are the requirements other than python I need to know to finish this task ?
- what is meant by handling XML files ?

**Comment by cglewis** [comment]
@harry-7 

- assuming you're familiar with docker, I'd recommend trying to spin up vent (https://github.com/cyberreboot/vent), once you have an instance of vent running, inside the interactive console you can add plugins (a github url, where this repo is a good example: https://github.com/CyberReboot/vent-plugins.git .  Once the plugin is installed, you can start the core (as explained in the readme in vent, and then you upload a file specific to that plugin's namespaces (currently only pcap files) and it will automatically run the apps instead of that plugin and process the files according to the plugin apps.
- actually, it doesn't have to be python, it can be in any language as long as it can run inside of a docker container and and read a file from the path being passed into the app as the first argument at runtime
- it can be handled anyway that is useful.  imagine getting an xml file and needing to parse though it, or perhaps a bunch of xml files and needing to find the values of the fields in each file.  perhaps you want to convert all of the xml files into json objects.  it's an example app, so take it where ever is interesting to you.
